### ISSUE TITLE
Typed.js not wotking on GitHub Pages. Working well on localhost.

### ISSUE THREAD

**Issue by mittrayash** [mittrayash/mittrayash.github.io#1]
## Localhost Preview  
![1](https://user-images.githubusercontent.com/22816365/31531043-0b858dbe-b002-11e7-9176-0a59215ff78e.png)
![2](https://user-images.githubusercontent.com/22816365/31531044-0bb704de-b002-11e7-9ca8-96f7dc0b00b6.png)
![3](https://user-images.githubusercontent.com/22816365/31531045-0be54452-b002-11e7-8133-b5336dcc08d7.png)

## GitHub Pages Preview
![4](https://user-images.githubusercontent.com/22816365/31531083-575cc018-b002-11e7-9649-3c5c819eff22.png)

**Comment by iknityanand** [comment]
can i try ?

**Comment by mittrayash** [comment]
@iknityanand Sure, you can.

**Comment by iknityanand** [comment]
on it! :)
